#application io.tiklab.postin.config
app:
  name: postin

spring:
  profiles:
    active: prd

DATA_HOME: ${user.home}/tiklab/${app.name}

#web 
server:
  port: 8080

#dal 
#jdbc:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://172.12.1.16:3306/tiklab_postin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  username: root
#  password: darth2020

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.13.1.13:5432/tiklab_postin?stringtype=unspecified
  username: postgres
  password: darth2020

#dfs 
dfs:
  server:
    enable: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs 
dcs:
  server:
    enable: false
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dss 
dss:
  server:
    enable: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

#integration 
homes:
  address: http://172.11.1.11:8080

#plugin 
plugin:
  path: ${DATA_HOME}/plugin

#licences 
licences:
  path: ${DATA_HOME}/licences

application: postin

file:
  path: http://file.tiklab.net

base:
  url:  http://postin-ce.tiklab.net

eas:
  embbed:
    enable: false
  address:  http://eas-ce.tiklab.net

postgresql:
  database: tiklab_postin
  embbed:
    enable: false