#application io.thoughtware.postin.config
app:
  name: postin
spring:
  profiles:
    active: prd

DATA_HOME: /opt/thoughtware/postin/postin

#io.thoughtware.teston.web
server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.13.1.13:5432/tiklab_postin?stringtype=unspecified
  username: postgres
  password: darth2020

#dcs 
dcs:
  server:
    enabled: false
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

#dfs config
dfs:
  server:
    #    enabled: true
    #    mode:server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 172.10.1.11:4000
    bucket: ${app.name}


soular:
  embbed:
    enable: false
  address:  http://eas-ce.tiklab.net

#plugin 
plugin:
  path: ${DATA_HOME}/plugin

#licences 
licences:
  path: ${DATA_HOME}/licences

base:
  url:  http://postin-ce.tiklab.net


file:
  path:
homes:
  address: http://192.168.10.7

backups:
  dir:  /data/postin
  time: 0 0 2 * * ?