#application config
app:
  name: doublekit-apibox
spring:
  profiles:
    active: dev

#web config
tomcat:
  port: 8080

#dal config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://172.10.1.10:3306/darth_apibox?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  username: root
  password: darth2020

#storege config
DATA_HOME: ${user.home}/doublekit/${app.name}

#dfs config
dfs:
  mode: server
  port: 5000
  path: ${DATA_HOME}/data/dfs
  url: server://127.0.0.1:5000/default

#dcs config
dcs:
  mode: server
  port: 6000
  path: ${DATA_HOME}/data/dcs
  url: server://127.0.0.1:6000/default

#dss config
dss:
  mode: server
  port: 7000
  path: ${DATA_HOME}/data/dss
  url: server://127.0.0.1:7000/default

#rpc config
rpc:
  server:
    port: 8000

#auth config
#auth:
#  type: acc
#  acc:
#    address: http://192.168.0.1:4001
#    service:
#      address: 192.168.0.16:8000

#integration config
homes:
  address: http://192.168.0.18:8080
  service:
    address: 192.168.0.18:8000

#plugin config
plugin:
  path: ${DATA_HOME}/plugin

#licences config
licences:
  path: ${APP_HOME}/licences