#application config
app:
  name: doublekit-apibox
spring:
  profiles:
    active: dev

#web config
server:
  port: 8080

#rpc config
#rpc:
#  server:
#    port: 8000

#dal config
jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://172.10.1.10:3306/darth_apibox?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  username: root
  password: darth2020

#storege config
DATA_HOME: ${user.home}/doublekit/${app.name}

#dfs config
dfs:
  server:
    mode: standalone
    port: 5000
    datapath: ${DATA_HOME}/data/dfs
  client:
    url: standalone://127.0.0.1:5000/default

#dcs config
dcs:
  server:
    mode: standalone
    port: 6000
    datapath: ${DATA_HOME}/data/dcs
  client:
    url: standalone://127.0.0.1:6000/default

#dss config
dss:
  server:
    mode: standalone
    port: 7000
    datapath: ${DATA_HOME}/data/dss
  client:
    url: standalone://127.0.0.1:7000/default

#auth config
#auth:
#  type: acc
#  address: http://192.168.0.1:4001

#integration config
homes:
  address: http://192.168.0.18:8080

#project:
#  address: http://127.0.0.1:8081

#plugin config
plugin:
  path: ${DATA_HOME}/plugin

#licences config
licences:
  path: ${APP_HOME}/licences