#application config
app:
  name: doublekit-apibox
spring:
  profiles:
    active: dev

PROJECT_HOME: ${user.home}/doublekit/${app.name}

#web config
server:
  port: 8080

#dal config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://172.11.1.10:3306/darth_apibox?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  username: root
  password: darth2020

#dss config
dss:
  server:
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#auth config
#auth:
#  type: acc
#  address: http://portal-ce.test.doublekit.net

#integration config
homes:
  address: http://172.11.1.11:8080

#plugin config
plugin:
  path: ${PROJECT_HOME}/plugin

#licences config
licences:
  path: ${APP_HOME}/licences

application: apibox