#application config
app:
  name: doublekit-apibox
spring:
  profiles:
    active: prd

PROJECT_HOME: ${user.home}/doublekit/${app.name}

#web config
server:
  port: 8080

#dal config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://172.12.1.16:3306/darth_apibox?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  username: root
  password: darth2020

#dfs config
dfs:
  server:
    mode: server
    port: 4000
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dss config
dss:
  server:
    mode: server
    port: 6000
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

#auth config
#auth:
#  type: acc
#  address: http://portal-ce.test.doublekit.net

#integration config
homes:
  address: http://172.19.6.134:8001

#plugin config
plugin:
  path: ${PROJECT_HOME}/plugin

#licences config
licences:
  path: ${PROJECT_HOME}/licences

application: apibox