#application io.tiklab.postin.config
app:
  name: postin

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml

DATA_HOME: ${user.home}/tiklab/${app.name}

#web
server:
  port: 8080

#dal
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tiklab_postin?stringtype=unspecified
  username: postgres
  password: darth2020


#dfs
dfs:
  server:
    enable: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs
dcs:
  server:
    enable: false
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dss
dss:
  server:
    enable: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

#integration
homes:
  address: http://172.11.1.11:8080

#plugin
plugin:
  path: ${DATA_HOME}/plugin

#licences
licences:
  path: ${DATA_HOME}/licences

application: postin

file:
  path: http://file.tiklab.net

base:
  url: http://

eas:
  embbed:
    enable: true
#  address:

postgresql:
  database: tiklab_postin
  embbed:
    enable: true