#application io.tiklab.postin.config
app:
  name: postin
spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml

DATA_HOME: /opt/tiklab/postin/postin

#web
server:
  port: 8080

#dal
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tiklab_postin?stringtype=unspecified
  username: postgres
  password: darth2020


#dcs
dcs:
  server:
    enabled: false
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

#plugin
plugin:
  path: ${DATA_HOME}/plugin

#licences
licences:
  path: ${DATA_HOME}/licences

base:
  url: http://

eas:
  embbed:
    enable: true
#  address:

postgresql:
  database: tiklab_postin
  embbed:
    enable: false
#  db:
#    port: 5432
#    username: postgres
#    password: darth2020
#    address: ${DATA_HOME}/postgresql