#application net.tiklab.postin.config
app:
  name: tiklab-postin

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml

PROJECT_HOME: ${user.home}/tiklab/${app.name}

#web net.tiklab.testondriver.config
server:
  port: 8080

#dal net.tiklab.testondriver.config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/tiklab_postin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: darth2020

#dfs net.tiklab.testondriver.config
dfs:
  server:
    enable: false
    mode: server
    port: 4000
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs net.tiklab.testondriver.config
dcs:
  server:
    enable: false
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dss net.tiklab.testondriver.config
dss:
  server:
    enable: false
    mode: server
    port: 6000
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

#integration net.tiklab.testondriver.config
homes:
  address: http://172.11.1.11:8080

#plugin net.tiklab.testondriver.config
plugin:
  path: ${PROJECT_HOME}/plugin

#licences net.tiklab.testondriver.config
licences:
  path: ${PROJECT_HOME}/licences

application: postin

file:
  path: http://file.tiklab.net

eas:
  embbed:
    enable: false
  address: http://eas-ce.tiklab.net

mysql:
  database: tiklab_postin
  embbed:
    enable: true