app:
  name: postin
spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml

server:
  port: 8300

APP_HOME: ${user.home}
DATA_HOME: /opt/tiklab/tiklab-postin

#db
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tiklab_postin?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  database: tiklab_postin
  embbed:
    enable: true
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#dcs
dcs:
  server:
    enabled: true
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

soular:
  embbed:
    enable: true
#  address:


#licences
licences:
  path: ${DATA_HOME}/licences

base:
  url: http://

backups:
  dir:  /data/postin
  time: 0 0 2 * * ?


