#application io.tiklab.postin.config
app:
  name: postin

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml

PROJECT_HOME: ${user.home}/tiklab/${app.name}

#web
server:
  port: 8080

#dal
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/tiklab_postin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: darth2020

#dfs
dfs:
  server:
    enable: false
    mode: server
    port: 4000
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs
dcs:
  server:
    enable: false
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dss
dss:
  server:
    enable: false
    mode: server
    port: 6000
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

#integration
homes:
  address: http://172.11.1.11:8080

#plugin
plugin:
  path: ${PROJECT_HOME}/plugin

#licences
licences:
  path: ${PROJECT_HOME}/licences

application: postin

file:
  path: http://file.tiklab.net

base:
  url: http://192.168.10.18:3000

eas:
  embbed:
    enable: true
#  address: eas-ce.tiklab.net

postgresql:
  database: tiklab_postin
  embbed:
    enable: true