#application config
app:
  name: tiklab-postin
spring:
  profiles:
    active: dev

PROJECT_HOME: ${user.home}/tiklab/${app.name}

#web config
server:
  port: 8080

#dal config
jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://172.10.1.10:3306/tiklab_postin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  username: root
  password: darth2020


#dfs config
dfs:
  server:
    mode: server
    port: 4000
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dss config
dss:
  server:
    mode: server
    port: 6000
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

#auth config
#auth:
#  type: acc
#  address: http://192.168.10.6:8080

#integration config
homes:
  address: http://192.168.10.19:8080

#project:
#  address: http://127.0.0.1:8081

#plugin config
plugin:
  path: ${PROJECT_HOME}/plugin

#licences config
licences:
  path: ${PROJECT_HOME}/licences

application: postin

file:
  path: http://file.dev.tiklab.net