#application com.tiklab.testondriver.config
app:
  name: tiklab-postin
spring:
  profiles:
    active: prd

PROJECT_HOME: ${user.home}/tiklab/${app.name}

#web com.tiklab.testondriver.config
server:
  port: 8082

#dal com.tiklab.testondriver.config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://172.12.1.16:3306/tiklab_postin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  username: root
  password: darth2020

#dfs com.tiklab.testondriver.config
dfs:
  server:
    mode: server
    port: 4005
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4005
    bucket: ${app.name}

#dcs com.tiklab.testondriver.config
dcs:
  server:
    mode: server
    port: 5005
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5005
    bucket: ${app.name}

#dss com.tiklab.testondriver.config
dss:
  server:
    mode: server
    port: 6005
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6005
    bucket: ${app.name}

#auth com.tiklab.testondriver.config
#auth:
#  type: acc
#  address: http://portal-ce.test.tiklab.net

#integration com.tiklab.testondriver.config
homes:
  address: http://172.19.6.134:8001

#plugin com.tiklab.testondriver.config
plugin:
  path: ${PROJECT_HOME}/plugin

#licences com.tiklab.testondriver.config
licences:
  path: ${PROJECT_HOME}/licences

application: postin

file:
  path: http://file.tiklab.net