#application 
app:
  name: postin
spring:
  profiles:
    active: demo

DATA_HOME: /opt/thoughtware/postin/postin

#web 
server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postin?stringtype=unspecified
  username: postgres
  password: darth2020

#dcs 
dcs:
  server:
    enabled: true
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

#dfs config
dfs:
  server:
    #    enabled: true
    #    mode:server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 172.10.1.11:4000
    bucket: ${app.name}

darth:
  embbed:
    enable: false
  address: http://darth-ce.demo.thoughtware.net

#plugin 
plugin:
  path: ${DATA_HOME}/plugin

#licences 
licences:
  path: ${DATA_HOME}/licences

base:
  url: http://postin-ce.demo.thoughtware.net

postgresql:
  database: postin
  embbed:
    enable: true
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql


file:
  path:
homes:
  address: http://192.168.10.7

backups:
  dir:  /data/postin
  time: 0 0 2 * * ?