#application io.tiklab.postin.config
app:
  name: postin
spring:
  profiles:
    active: dev

postin:
  scan:
    package: io.tiklab
  report:
    workspaceId: c51c82d60d12
    server: http://192.168.10.3:8090



DATA_HOME: ${user.home}/tiklab/${app.name}

#io.tiklab.teston.web io.tiklab.postin.config
server:
  port: 8080

#dal io.tiklab.postin.config
#jdbc:
#  driverClassName: com.mysql.cj.jdbc.Driver
##  172.10.1.10
#  url: jdbc:mysql://172.10.1.10:3306/tiklab_postin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  username: root
#  password: darth2020
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_postin?stringtype=unspecified
  username: postgres
  password: darth2020

homes:
  address: http://192.168.10.14:8080

#project:
#  address: http://127.0.0.1:8081

#plugin
plugin:
  path: ${DATA_HOME}/plugin

#licences
licences:
  path: ${DATA_HOME}/licences

application: postin

file:
  path: http://file.dev.tiklab.net

base:
  url: http://192.168.10.3:3000

soular:
  embbed:
    enable: true
#  address: http://soular.dev.tiklab.net
#  web:
#    address: http://soular.dev.tiklab.net


postgresql:
  database: tiklab_postin
  embbed:
    enable: false

