#application 
app:
  name: postin
spring:
  profiles:
    active: demo

DATA_HOME: /opt/tiklab/postin/postin

#web 
server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postin?stringtype=unspecified
  username: postgres
  password: darth2020

#dcs 
dcs:
  server:
    enabled: true
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

eas:
  embbed:
    enable: false
  address: http://eas-ce.demo.tiklab.net

#plugin 
plugin:
  path: ${DATA_HOME}/plugin

#licences 
licences:
  path: ${DATA_HOME}/licences

base:
  url: http://postin-ce.demo.tiklab.net

postgresql:
  database: postin
  embbed:
    enable: true
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql


file:
  path:
homes:
  address: http://192.168.10.7

