#application 
app:
  name: tiklab-postin
spring:
  profiles:
    active: demo

PROJECT_HOME: ${user.home}/tiklab/${app.name}

#web 
server:
  port: 8080


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.12.1.10:5432/tiklab_postin?stringtype=unspecified
  username: postgres
  password: darth2020


#dfs 
dfs:
  server:
    enable: false
    mode: server
    port: 4000
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs 
dcs:
  server:
    enable: false
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dss 
dss:
  server:
    enable: false
    mode: server
    port: 6000
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

#integration 
homes:
  address: http://172.11.1.11:8080

#plugin 
plugin:
  path: ${PROJECT_HOME}/plugin

#licences 
licences:
  path: ${PROJECT_HOME}/licences

application: postin

file:
  path: http://file.demo.tiklab.net

base:
  url: http://postin-ce.demo.tiklab.net

eas:
  embbed:
    enable: false
  address: http://eas-ce.demo.tiklab.net

postgresql:
  database: tiklab_postin
  embbed:
    enable: false