#application 
app:
  name: postin
spring:
  profiles:
    active: demo

DATA_HOME: /opt/tiklab/postin/postin

#web 
server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.12.1.10:5432/tiklab_postin?stringtype=unspecified
  username: postgres
  password: darth2020



#dcs 
dcs:
  server:
    enabled: false
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200


#integration 
homes:
  address: http://homes-api.demo.tiklab.net

eas:
  embbed:
    enable: false
  address: http://eas-ce.demo.tiklab.net

#plugin 
plugin:
  path: ${DATA_HOME}/plugin

#licences 
licences:
  path: ${DATA_HOME}/licences

application: postin

file:
  path: http://file.demo.tiklab.net

base:
  url: http://postin-ce.demo.tiklab.net

