app:
  name: postin
spring:
  profiles:
    active: dev

#启动端口
server:
  port: 8090

DATA_HOME: ${user.home}/tiklab/tiklab-${app.name}

#db
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_postin?stringtype=unspecified
  username: postgres
  password: darth2020

#jdbc:
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://172.10.1.10:3306/tiklab_postin?characterEncoding=utf8&useSSL=false
#  username: root
#  password: darth2020


postgresql:
  database: tiklab_postin
  embbed:
    enable: false
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#dcs
dcs:
  server:
    enabled: true
    port: 5000
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

#soular统一登录配置
auth:
  type: local #(local:本地登录  soular:统一登录)
  soular:
    address: http://192.168.10.15:8080

external:
  url: http://192.168.10.22:8090


postin-agent:
  name: agent-default   # 唯一
  #  tenant: z2z5x9a5
  #  websocket-url: "ws://172.13.1.18:8090/websocket"
  websocket-url:  "ws://localhost:8090/websocket"
#  websocket-url: "ws://testhubo.tiklab.cn/websocket"
#  websocket-url: "ws://192.168.10.34:8082/websocket"