#application io.tiklab.postin.config
app:
  name: tiklab-postin
spring:
  profiles:
    active: dev


PROJECT_HOME: ${user.home}/tiklab/${app.name}

#web io.tiklab.postin.config
server:
  port: 8080

#dal io.tiklab.postin.config
jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
#  172.10.1.10
  url: jdbc:mysql://172.10.1.10:3306/tiklab_postin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: darth2020


#dfs io.tiklab.postin.config
dfs:
  server:
    enable: false
    mode: server
    port: 4000
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs io.tiklab.postin.config
dcs:
  server:
    enable: false
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dss io.tiklab.postin.config
dss:
  server:
    enable: false
    mode: server
    port: 6000
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}


homes:
  address: http://192.168.10.19:8080

#project:
#  address: http://127.0.0.1:8081

#plugin
plugin:
  path: ${PROJECT_HOME}/plugin

#licences
licences:
  path: ${PROJECT_HOME}/licences

application: postin

file:
  path: http://file.dev.tiklab.net

base:
  url: http://192.168.10.18:3000

eas:
  embbed:
    enable: false
  address: http://192.168.10.11:8081
  web:
    address: http://192.168.10.11:3001

mysql:
  database: tiklab_postin
  embbed:
    enable: false