app:
  name: postin
spring:
  profiles:
    active: dev

#启动端口
server:
  port: 8090

APP_HOME: ${user.home}
DATA_HOME: ${user.home}/tiklab/tiklab-${app.name}

#db
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_postin?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  database: tiklab_postin
  embbed:
    enable: false
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#dcs
dcs:
  server:
    enabled: true
    port: 5000
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

#soular统一登录配置
soular:
  embbed:
    enable: true
  address: http://192.168.10.42:8080
  web:
    address: http://192.168.10.42:8080

#licences
licences:
  path: ${DATA_HOME}/licences

base:
  url: http://192.168.10.34:8090

#数据库备份
backups:
  dir:  /data/postin
  time: 0 0 2 * * ?


#postin:
#  enable: true
#  scan:
#    package: io.tiklab
#  report:
#    workspaceId: 80c5a5b08417
#    server: http://192.168.10.21:8090

