#application io.tiklab.postin.config
app:
  name: postin
spring:
  profiles:
    active: dev

DATA_HOME: ${user.home}/tiklab/${app.name}

server:
  port: 8090

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_postin?stringtype=unspecified
  username: postgres
  password: darth2020

dcs:
  server:
    enabled: true
    port: 5000
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

eas:
  embbed:
    enable: true
#  address: http://eas.dev.tiklab.net
#  web:
#    address: http://eas.dev.tiklab.net

#plugin
plugin:
  path: ${DATA_HOME}/plugin

#licences
licences:
  path: ${DATA_HOME}/licences

base:
  url: http://192.168.10.3:3000
